---
- group: name={{ fluentd.group }} system=yes
- user: name={{ fluentd.user }} group={{ fluentd.group }} system=yes

- file: path={{ fluentd.log_dir }} state=directory owner={{ fluentd.user }}
- file: path={{ fluentd.config_dir }} state=directory owner={{ fluentd.user }}
- file: path={{ fluentd.log_dir }}/s3/{{ fluentd_s3_path_prefix }} state=directory owner={{ fluentd.user }}

- name: configure
  template: src=fluentd.conf.j2 dest=/etc/td-agent/td-agent.conf owner={{ fluentd.user }}
  notify:
    - restart td-agent
