---
- include: install.yml
  tags:
    - fluentd
    - fluentd-install

- include: config.yml
  tags:
    - fluentd
    - fluentd-configure

- include: rubybs.yml
  tags:
    - fluentd
    - fluentd-hacks
