---

- name: install dependencies...
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - python-pycurl

- name: installing the td-agent
  shell: curl -L http://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh | sh
  when: tdAgentPath.stdout == "~none~"
  notify:
    - restart td-agent

- name: installing td-agent's kafka plugin
  shell: td-agent-gem install fluent-plugin-kafka
  when: tdAgentKafkaPlugin.stdout.find('kafka') == -1
  notify:
    - restart td-agent
