---

- name: restart td-agent
  service: name=td-agent state=restarted enabled=yes

- name: reload monit
  service: name=monit state=reloaded

- name: monitor fluentd
  monit: name=td-agent state=monitored
